# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/mirror/docker/library/node:22

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json /app/
RUN npm ci
RUN npm install -g @angular/cli

# Copy the site to the working directory
COPY . /app

# Run the site in mock mode
CMD ng serve --host 0.0.0.0 --port 80 --configuration mock --poll 100
