name: Generate ARM Template

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.bicep'

permissions:
  contents: write

jobs:
  generateArmTemplate:
    name: Generate ARM Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Bicep build ARM template
        uses: Azure/bicep-build-action@d2a88e5c7150cd562f3e8b8f361560db2cb4d5c5 # v1.0.1
        with:
          bicepFilePath: ./control-plane/main.bicep
          outputFilePath: azuredeploy.json
      - name: Commit Generated ARM Template
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: Commit generated ARM template