name: Generate ARM Template

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.bicep'

permissions:
  contents: write

jobs:
  generateArmTemplate:
    name: Generate ARM Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Bicep build ARM template
        uses: Azure/bicep-build-action@c333f970fb0daae2241062b5b7acf30a97f696c9 # v1.0.0
        with:
          bicepFilePath: ./control-plane/main.bicep
          outputFilePath: azuredeploy.json
      - name: Commit Generated ARM Template
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: Commit generated ARM template