name: Release

on:
  release:
    types: [published]

jobs:
  validate:
    name: Validation
    uses: ./.github/workflows/validate.yml
  create_assets_for_release:
    name: Create Assets for Release
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Tokenize portal version
        uses: cschleiden/replace-tokens@63252851d87eb5cb853019ba8538b5c51813779d # v1.4
        with:
          files: '["**/control-plane/experiencelab.sh"]'
        env:
          Build.BuildNumber: ${{ github.ref_name }}

      - name: Compress portal
        run: tar -czvf developer-portal.tar.gz developer-portal

      - name: Compress REST scripts
        run: zip -r rest-scripts.zip rest-scripts

      - name: Bicep build ARM template
        uses: Azure/bicep-build-action@d2a88e5c7150cd562f3e8b8f361560db2cb4d5c5 # v1.0.1
        with:
          bicepFilePath: ./control-plane/main.bicep
          outputFilePath: ./azuredeploy.json

      - name: Copy data load Dockerfile with release name
        run: cp data-load/open-test-data/Dockerfile Dockerfile-open-test-data

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            developer-portal.tar.gz
            rest-scripts.zip
            azuredeploy.json
            data-load/open-test-data/downloadTnoData.sh
            data-load/open-test-data/template.json
            data-load/open-test-data/loader.py
            Dockerfile-open-test-data
            control-plane/Dockerfile
            control-plane/containerRun.sh
            control-plane/experiencelab.sh
